### ISSUE TITLE
Get the home partition

### ISSUE THREAD

**Issue by sindresorhus** [kevva/xdg-trashdir#1]
https://github.com/sindresorhus/trash/issues/15#issuecomment-61252192

**Comment by kevva** [comment]
@passy, are you aware of any reliable way to get the home partition in Linux?

**Comment by passy** [comment]
@kevva `df` seems like a portable workaround if used with `-P`.

The "correct" way on Linux would be to stat the file, get the device number of the file through the `st_dev` attribute on the struct and map that to whatever device it is in `/proc/mounts`.
