### ISSUE TITLE
Dependency @sindresorhus/df

### ISSUE THREAD

**Issue by Knorcedger** [kevva/xdg-trashdir#4]
I ended up here after trying to install [np](https://github.com/sindresorhus/np) but i kept getting the warning 
> Couldn't install optional dependency: Invalid name: "@sindresorhus/df"  

and the install was not happening. After trying to install the dependencies one my one, i found that its this package that requests that dependency. Not sure why (and if) that warning prevents the packages installation, but I suppose that's something to be fixed, right?

I have my logs here -> http://pastebin.com/ArLR6Smy
I'm on Ubuntu 15.10, node 5.3, npm 3.3.12

**Comment by sindresorhus** [comment]
Try upgrading to latest version of npm. This is a problem with npm, and not this package. Use the [npm issue tracker](https://github.com/npm/npm/issues) for npm support.

**Comment by Knorcedger** [comment]
Tnx, that fixed it. I suppose its some kind of a new feature I need to learn :)

**Comment by airtonix** [comment]
@Knorcedger can you link the ticket you made on the npm repo?

we have this same problem due to installing `trash-cli`.

**Comment by Knorcedger** [comment]
It was not an issue, I just had to upgrade my npm version
